name: ufrgs_app
description: "An app for UFRGS Students."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  webview_flutter: ^4.12.0
  cupertino_icons: ^1.0.8
  http: ^1.4.0
  logger: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true